import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import PNavbar from './@PNavbar/page';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>      
      <PNavbar/> {/* Rendering the Navbar component */}
        {children}
      </body>
    </html>
  );
}
